name: vrikka
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:  
  dio:

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.10

  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.8  

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sound/
 
  fonts:
     - family: Poppins
       fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
