// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFepElssJKMi7ioj4TlqSjD2nExvNO4k',
    appId: '1:855004098802:web:88d49a836936b1e15b606b',
    messagingSenderId: '855004098802',
    projectId: 'vrikka-95618',
    authDomain: 'vrikka-95618.firebaseapp.com',
    databaseURL: 'https://vrikka-95618-default-rtdb.firebaseio.com',
    storageBucket: 'vrikka-95618.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCig609jbDudFtvQWrG-IxrvnUKBE5TeEg',
    appId: '1:855004098802:android:3f3661f8b851a1b75b606b',
    messagingSenderId: '855004098802',
    projectId: 'vrikka-95618',
    databaseURL: 'https://vrikka-95618-default-rtdb.firebaseio.com',
    storageBucket: 'vrikka-95618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAod3rjptL4x9oV5CunMBT4O35Hw4eHKmU',
    appId: '1:855004098802:ios:d6d176c9d3ad2cab5b606b',
    messagingSenderId: '855004098802',
    projectId: 'vrikka-95618',
    databaseURL: 'https://vrikka-95618-default-rtdb.firebaseio.com',
    storageBucket: 'vrikka-95618.appspot.com',
    iosBundleId: 'com.example.vrikka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAod3rjptL4x9oV5CunMBT4O35Hw4eHKmU',
    appId: '1:855004098802:ios:bd667bc486fdf8b45b606b',
    messagingSenderId: '855004098802',
    projectId: 'vrikka-95618',
    databaseURL: 'https://vrikka-95618-default-rtdb.firebaseio.com',
    storageBucket: 'vrikka-95618.appspot.com',
    iosBundleId: 'com.example.vrikka.RunnerTests',
  );
}
